version: 2

jobs:
  build:
    working_directory: /home/redoc

    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker

      # install OS dependencies
      - run: apk update && apk upgrade && apk add --no-cache bash git openssh py-pip && pip install docker-compose

      - checkout

      # run build test
      - run: .circleci/build.sh

      # deploy the build (if on a deployment branch)
      - run: .circleci/deploy.sh
