# Usage:
# docker-compose up -d

redoc:
  container_name: redoc
  image: reactioncommerce/redoc:latest
  links:
    - mongo
  ports:
    - "3000:3000"
  environment:
    ROOT_URL: "http://localhost"
    MONGO_URL: "mongodb://mongo:27017/redoc"

mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
